Release Notes for v0.5.0
secure-device-onboard/release-fidoiot pull request #2
Opened 2021-04-28 15:19 UTC by trbehera

Signed-off-by: Behera, Tushar Ranjan <tushar.ranjan.behera@intel.com>

2021-04-28 15:33 UTC, Darshini-Parikh93 submitted a review, later dismissed

2021-04-28 15:37 UTC, v-Vasavi submitted a review, later dismissed

2021-04-28 15:38 UTC, prateekcr submitted a review, later dismissed

2021-04-28 19:04 UTC, johneasterday commented on release-notes-v0.5.0.md
> +  * EPID Verificatio Service: [epid-verification-service](https://github.com/secure-device-onboard/epid-verification-service) is a wrapper service written on top of EPID SDK to assist FDO Rendezvous
typo - Verificatio -> Verification

2021-04-28 19:06 UTC, johneasterday commented on release-notes-v0.5.0.md
> +  * Endpoints to download cryptomaterial tar ball and cryptomaterial signature files
cryptomaterial -> crypto material

2021-04-29 02:04 UTC, KiranSukhavasi requested changes

2021-04-29 02:04 UTC, KiranSukhavasi commented on release-notes-v0.5.0.md
> +  * Protocol Reference Implementation (PRI): [pri-fidoiot](https://github.com/secure-device-onboard/pri-fidoiot) is a JAVA based implementation of all the components specified in the FDO Proposed Sta
Do we need to mention about 0.5-rel branch here or not required?

2021-04-29 02:04 UTC, KiranSukhavasi commented on release-notes-v0.5.0.md
> +  * Test: [test-fidoiot](https://github.com/secure-device-onboard/test-fidoiot) implements a test-suite that gets executed as part of continuous integration pipeline.
This "test-fidoiot" link is showing Page not found error. Do i need any permission to access this repo? I assume these tests are in Gitlab. Could we recheck this?

2021-04-29 02:04 UTC, KiranSukhavasi commented on release-notes-v0.5.0.md
> +**pri-fidoiot**: Support for Intel OnDie ECDSA based device attestation has been included.
As we are pushing DAL release to next week, Do we need to mention the support for OnDie in the notes here?

2021-04-29 02:04 UTC, KiranSukhavasi commented on release-notes-v0.5.0.md
> +**test-fidoiot**: Provides the TestNG based test-suite that is executed for validating the pull requests raised for `pri-fidoiot` and `client-sdk-fidoiot` repositories.
i couldn't access test-fidoiot. Please let me know if this is applicable!!

2021-04-29 02:04 UTC, KiranSukhavasi commented on release-notes-v0.5.0.md
> +### Known Issues
Do you want to update any known issues from the outstanding defects? If so, we can review the defects and put few incase...

2021-04-29 09:37 UTC, DukeDavis12 commented on release-notes-v0.5.0.md
> +  * Client SDK: [client-sdk-fidoiot](https://github.com/secure-device-onboard/client-sdk-fidoiot) is a C based implementation for the device component specified in the FDO Proposed Standard. Addition
Additionally --> Additionally,

2021-04-29 09:37 UTC, DukeDavis12 commented on release-notes-v0.5.0.md
> +**epid-verification-service**: It exposes following REST end-points.
exposes following --> exposes the following

2021-04-29 09:37 UTC, DukeDavis12 commented on release-notes-v0.5.0.md
> +  * Endpoints to download cryptomaterial tar ball and cryptomaterial signature files
tar ball --> tarball

2021-04-29 09:37 UTC, DukeDavis12 commented on release-notes-v0.5.0.md
> +**pri-fidoiot**: TLS support has been enabled for the Docker containers provided within `components-samples\demo`.
Won't TLS support come in the `New features` section?

2021-04-29 09:39 UTC, trbehera commented on release-notes-v0.5.0.md
> +  * Test: [test-fidoiot](https://github.com/secure-device-onboard/test-fidoiot) implements a test-suite that gets executed as part of continuous integration pipeline.
test-fidoiot repo would be pushed out to GitHub in a couple of days.

2021-04-29 09:40 UTC, trbehera commented on release-notes-v0.5.0.md
> +**pri-fidoiot**: Support for Intel OnDie ECDSA based device attestation has been included.
No, that is not part of opensource release.

2021-04-29 09:56 UTC, DukeDavis12 approved these changes

2021-04-29 09:58 UTC, v-Vasavi approved these changes

2021-04-29 09:58 UTC, v-Vasavi approved these changes

2021-04-29 09:59 UTC, KiranSukhavasi approved these changes

2021-04-29 10:00 UTC, DukeDavis12 approved these changes

2021-04-29 10:01 UTC, merged